site_name: Islamic State
theme:
  name: material
  palette:
    scheme: slate
    primary: white
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.instant
markdown_extensions:
    - pymdownx.tabbed:
        alternate_style: true
    - attr_list
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
extra:
    social:
        - icon: fontawesome/solid/paper-plane
          link: t.me/flsdjhfskjdhfskdjfhsdkjfhskjf
    generator: false
nav:
    - Security:
        - security/index.md